export const Users = [
    {
        id: 1,
        profilePicture: "persons/person1.jpg",
        username: "The UnderTaker",
    },
    {
        id: 2,
        profilePicture: "persons/person2.jpg",
        username: "John Cena",
    },
    {
        id: 3,
        profilePicture: "persons/person3.jpg",
        username: "Ronda Rousey",
    },
    {
        id: 4,
        profilePicture: "persons/person 4.jpg",
        username: "Alexa bliss",
    },
    {
        id: 5,
        profilePicture: "persons/person5.jpg",
        username: "Asuka",
    },
    {
        id: 6,
        profilePicture: "persons/7.jpg",
        username: "Kurt Angle",
    },
    {
        id: 7,
        profilePicture: "persons/8.jpg",
        username: "Big Show",
    },
    {
        id: 8,
        profilePicture: "persons/9.jpg",
        username: "Kane",
    },
    {
        id: 9,
        profilePicture: "persons/10.jpg",
        username: "Jeff Hardy",
    },
    {
        id: 10,
        profilePicture: "persons/6.jpg",
        username: "Backey",
    },
];

export const posts = [
    {
        id: 1,
        desc: "Love for All,Hatred for None",
        photo: "assets/post/1.jpg",
        date: "5 mins ago",
        userId: 1,
        like: 32,
        Comment: 9,
    },
    {
        id: 2,
        photo: "assets/post/2.jpg",
        date: "15 mins ago",
        userId: 2,
        like: 2,
        Comment: 1,
    },
    {
        id: 3,
        photo: "assets/post/3.jpg",
        date: "15 mins ago",
        userId: 3,
        like: 20,
        Comment: 1,
    },
    {
        id: 4,
        photo: "assets/post/4.jpg",
        date: "5 mins ago",
        userId: 4,
        like: 26,
        Comment: 10,
    },
    {
        id: 5,
        photo: "assets/post/5.jpg",
        date: "1 mins ago",
        userId: 5,
        like: 19,
        Comment: 19,
    },
    {
        id: 6,
        photo: "assets/post/6.jpg",
        date: "4 mins ago",
        userId: 6,
        like: 80,
        Comment: 37,
    },
    {
        id: 7,
        photo: "assets/post/7.jpg",
        date: "15 mins ago",
        userId: 7,
        like: 7,
        Comment: 7,
    },
    {
        id: 8,
        photo: "assets/post/8.jpg",
        date: "36 mins ago",
        userId: 8,
        like: 222,
        Comment: 100,
    },
    {
        id: 9,
        photo: "assets/post/9.jpg",
        date: "16 mins ago",
        userId: 9,
        like: 2,
        Comment: 1,
    },
    {
        id: 10,
        photo: "assets/post/2.jpg",
        date: "15 mins ago",
        userId: 10,
        like: 2,
        Comment: 1,
    },
]